#!/bin/bash
# The privileged helper interrupted at each of the review's eight
# boundaries, recovering from the record alone.
set -eu
src=${CAMP_SRC:-$HOME/camp}
measure=${CAMP_MEASURE:-$src/measure}
env=${CAMP_ENV:-$HOME/campcheck}

cd "$src"
go build -tags camptest -o "$env/camp-barriers" ./cmd/camp
cd "$measure"
go run ./killmatrix -env "$env" -camp "$env/camp-barriers"
