#!/bin/bash
# The environment's name swapped under the helper at each of its
# resolutions, with a root-owned trap tree at the old name.
set -eu
src=${CAMP_SRC:-$HOME/camp}
measure=${CAMP_MEASURE:-$src/measure}
env=${CAMP_ENV:-$HOME/campcheck}

cd "$src"
go build -tags camptest -o "$env/camp-barriers" ./cmd/camp
cd "$measure"
go run ./renamerace -env "$env" -camp "$env/camp-barriers"
